// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymN7-YTag3gD04js11hZyZeg3nbR4dtQ',
    appId: '1:677491076017:web:238aaa5074c5ef249a2b90',
    messagingSenderId: '677491076017',
    projectId: 'traceit-916e7',
    authDomain: 'traceit-916e7.firebaseapp.com',
    storageBucket: 'traceit-916e7.firebasestorage.app',
    measurementId: 'G-GY5WVXDNZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0uJoU9mgA5CCGBKaWP7mucF144LpOIfY',
    appId: '1:677491076017:android:3b336ac7a9e296a49a2b90',
    messagingSenderId: '677491076017',
    projectId: 'traceit-916e7',
    storageBucket: 'traceit-916e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhjl-onP9pJ1NRDfW1QIvHyxP56kBd9U',
    appId: '1:677491076017:ios:2302b12768d0162a9a2b90',
    messagingSenderId: '677491076017',
    projectId: 'traceit-916e7',
    storageBucket: 'traceit-916e7.firebasestorage.app',
    iosBundleId: 'com.example.traceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuhjl-onP9pJ1NRDfW1QIvHyxP56kBd9U',
    appId: '1:677491076017:ios:2302b12768d0162a9a2b90',
    messagingSenderId: '677491076017',
    projectId: 'traceit-916e7',
    storageBucket: 'traceit-916e7.firebasestorage.app',
    iosBundleId: 'com.example.traceit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAymN7-YTag3gD04js11hZyZeg3nbR4dtQ',
    appId: '1:677491076017:web:d2e3490376203f139a2b90',
    messagingSenderId: '677491076017',
    projectId: 'traceit-916e7',
    authDomain: 'traceit-916e7.firebaseapp.com',
    storageBucket: 'traceit-916e7.firebasestorage.app',
    measurementId: 'G-KMGB6S6S58',
  );

}